### ISSUE TITLE
poor calibration result

### ISSUE THREAD

**Issue by ahandsomeperson** [JD-ETH/Remittance-Calibration#1]
Hi Guo!
I use your code to calibrate my VLP16 lidar intensity. However poor result happens
![选区_004](https://user-images.githubusercontent.com/33352875/56640013-94e1b380-66a4-11e9-8781-47f45f80093a.png)
Later I use your calibration file from QCAT dataset, but still, it seems not perfect
![图片](https://user-images.githubusercontent.com/33352875/56640325-4ed91f80-66a5-11e9-881d-dfbec22dbae3.png)
The right side is the calibrated pointcloud and the left is the original. There are some points with
 purple intensity after calibrated, who I think are the outliers. It seems that the velodyne lidar has already been calibrated. My calibration result shows worse performance than the original velodyne data. 
However, it seems QCAT dataset also have this issue.
![图片](https://user-images.githubusercontent.com/33352875/56643299-ee011580-66ab-11e9-9c31-057ee0a471ee.png)
The right(corrected) pointcloud has some blue intensity points while the left(original) does not. The two pointclouds are from QCAT pole local_scan_52.
I am not sure whether it is necessary to calibrate the intensity manually? Or something I understand wrong?
Looking forward to your reply!

**Comment by JD-ETH** [comment]
Hi there, sorry I just saw this issue.

- The calibration is individual to sensors so sadly it won't work for your LiDAR. 
- It is true that after calibration outliers shows up and it feels less intuitive when observe visually. interestingly enough though, the calibration appears to draw similar surfaces together: individually it seems to lose precision but pulling different beams closer to each other for similar surface at similar distances. 
```
Interestingly, ISHOT-C improves the overall recall rate by
giving up some precision at low τ , compared to ISHOT.
By mapping distinctive measurements to fewer statistically
dominant “true” values, calibration indeed helped bringing
similar surfaces closer in the descriptor space.
```
Maybe checkout the [paper](https://arxiv.org/pdf/1811.12646.pdf) where I used this result.
